app:
  name: "app"
  mode: "dev"
  port: 8088

log:
  level: "debug"
  filename: "app.log"
  max_size: 200
  max_age: 30
  max_backup: 7

mysql:
  # host: "127.0.0.1" # 如果在本地跑，改成127.0.0.1
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "" # 本地跑没有密码，若go run main.go 在本地跑，改为空密码
  dbname: "go_web_app_db"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  # host: "127.0.0.1" # 如果在本地跑，改成127.0.0.1
  host: "127.0.0.1"
  port: 6379
  user: "root"
  password: ""
  db: 0
  poor_size: 100

rabbitmq:
  host: "127.0.0.1"
  port: 5672
  user: "guest"
  password: "guest"
  vhost: "/"